### ISSUE TITLE
Implement the agent load generator input+integration

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent-inputs#22]
1. https://github.com/elastic/elastic-agent-inputs/issues/24
2. https://github.com/elastic/elastic-agent-inputs/issues/5
3. https://github.com/elastic/elastic-agent-inputs/issues/25
4. https://github.com/elastic/elastic-agent-inputs/issues/26
5. https://github.com/elastic/elastic-agent-inputs/issues/27
6. https://github.com/elastic/elastic-agent-inputs/issues/28
7. https://github.com/elastic/elastic-agent-inputs/issues/29
8. https://github.com/elastic/elastic-agent-inputs/issues/3
9. https://github.com/elastic/elastic-agent-inputs/issues/30
10. https://github.com/elastic/elastic-agent-inputs/issues/31
11. https://github.com/elastic/elastic-agent-inputs/issues/32
12. https://github.com/elastic/elastic-agent-inputs/issues/33
13. https://github.com/elastic/elastic-agent-inputs/issues/35
14. https://github.com/elastic/elastic-agent-inputs/issues/34
15. https://github.com/elastic/elastic-agent/issues/592

**Comment by belimawr** [comment]
I broke down the work into smaller issues, here is the, somehow, ordered list:
1. https://github.com/elastic/elastic-agent-inputs/issues/24
2. https://github.com/elastic/elastic-agent-inputs/issues/5
3. https://github.com/elastic/elastic-agent-inputs/issues/25
4. https://github.com/elastic/elastic-agent-inputs/issues/26
5. https://github.com/elastic/elastic-agent-inputs/issues/27
6. https://github.com/elastic/elastic-agent-inputs/issues/28
7. https://github.com/elastic/elastic-agent-inputs/issues/29
8. https://github.com/elastic/elastic-agent-inputs/issues/3
9. https://github.com/elastic/elastic-agent-inputs/issues/30
10. https://github.com/elastic/elastic-agent-inputs/issues/31
11. https://github.com/elastic/elastic-agent-inputs/issues/32
12. https://github.com/elastic/elastic-agent-inputs/issues/33
13. https://github.com/elastic/elastic-agent-inputs/issues/35
14. https://github.com/elastic/elastic-agent-inputs/issues/34
15. https://github.com/elastic/elastic-agent/issues/592

**Comment by jlind23** [comment]
Thanks @belimawr for the work. I moved those items to the issue's description.
