### ISSUE TITLE
Connecting and sending data to Shipper

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent-inputs#29]
Connect to the [Shipper](https://github.com/elastic/elastic-agent-shipper) and send data.

Acceptance criteria:
- [ ] Implement the V2 control protocol
- [ ] Abide to all defined configuration formats
- [ ] Support a simple console/file output that can be used for debugging development independently from the shipper

**Comment by cmacknz** [comment]
The shipper API is defined at https://github.com/elastic/elastic-agent-shipper-client/tree/main/api

The preliminary beats shipper client can be used as a reference and is defined at https://github.com/elastic/beats/tree/main/libbeat/outputs/shipper
